include:
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/userscript.yml"

check-types:
  allow_failure: true

build:
  artifacts:
    when: on_failure
    paths:
      - .userscripter-temp/
