include:
  - project: 'dropLoop/ci-templates'
    ref: master
    file: 'node/core.yml'
  - project: 'dropLoop/ci-templates'
    ref: master
    file: 'node/meta.yml'
  - project: 'dropLoop/ci-templates'
    ref: master
    file: 'node/dependencies.yml'
  - project: 'dropLoop/ci-templates'
    ref: master
    file: 'node/typescript.yml'

test:
  only:
    - never


build:
  stage: build
  image: node:14
  artifacts:
    paths:
      - ./dist
  script:
    - yarn install
    - NODE_ENV=production yarn build


push to main repo:
  image: jackzzz92/jq-httpie-git
  stage: publish
  dependencies:
    - build
  script:
    - |
      for relativeFilePath in dist/*; do
        filePath="$(basename -- "$relativeFilePath")"
        fileContents="$(cat $relativeFilePath)"
        httpVerb="POST"
        if http "HEAD" "$CI_API_V4_URL/projects/24681114/repository/files/$filePath" ref==master Private-Token:"$GITLAB_TOKEN" > /dev/null; then
          httpVerb="PUT"
        fi
        req_path="projects/24681114/repository/files/$filePath"
        jo branch=master author_email="$GITLAB_USER_EMAIL" author_name="$GITLAB_USER_NAME" commit_message="api update $filePath" content="$fileContents" | http --check-status --body "$httpVerb" "$CI_API_V4_URL/$req_path" Private-Token:"$GITLAB_TOKEN"
      done

stages:
  - test
  - build
  - publish
  - meta
